### ISSUE TITLE
Vagrant provision fails to install required packages

### ISSUE THREAD

**Issue by bmarchant** [zerebubuth/openstreetmap-cgimap#215]
When running `vagrant up` to build the vagrant VM, I get the following errors.
```
    xenial: Package libboost-filesystem-dev is not available, but is referred to by another package.
    xenial: This may mean that the package is missing, has been obsoleted, or
    xenial: is only available from another source
    xenial: 
    xenial: Package libboost-system-dev is not available, but is referred to by another package.
    xenial: This may mean that the package is missing, has been obsoleted, or
    xenial: is only available from another source
    xenial: E: Unable to locate package libpqxx-dev
    xenial: E: Unable to locate package libboost-regex-dev
    xenial: E: Unable to locate package libboost-date-time-dev
    xenial: E: Package 'libboost-filesystem-dev' has no installation candidate
    xenial: E: Package 'libboost-system-dev' has no installation candidate
    xenial: E: Unable to locate package libboost-locale-dev
    xenial: E: Unable to locate package libcrypto++-dev
    xenial: E: Couldn't find any package by regex 'libcrypto++-dev'
    xenial: Reading package lists...
    xenial: Building dependency tree...
    xenial: 
    xenial: Reading state information...
    xenial: E: Unable to locate package postgis
    xenial: sudo: unknown user: postgres
    xenial: sudo: unable to initialize policy plugin
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
This is solved by simply adding `apt-get update;` to the `scripts/provision.sh` file before calling `apt-get install`.
