### ISSUE TITLE
Lighthttpd FastCGI unable to start due to permission denied

### ISSUE THREAD

**Issue by reshadshuvo123** [zerebubuth/openstreetmap-cgimap#394]
When I execute the docker-compose file, all services mentioned in it work properly except for the lighttpd service, which encounters an issue (permission denied). When I run docker compose file, I am getting this

```
 ✔ Container troubleshoot-lighttpd-1  Created                                                                                                                          0.0s
Attaching to troubleshoot-lighttpd-1
troubleshoot-lighttpd-1  | Starting lighttpd server...
troubleshoot-lighttpd-1  | 2024-04-17 20:51:39: (server.c.1568) server started (lighttpd/1.4.64)
troubleshoot-lighttpd-1  | 2024-04-17 20:51:39: (gw_backend.c.1619) invalid "bin-path" => "/openstreetmap-cgimap" (check that file exists, is regular file, and is executable by lighttpd)
troubleshoot-lighttpd-1  | 2024-04-17 20:51:39: (gw_backend.c.530) connect /tmp/map-fastcgi.socket-0: Connection refused
troubleshoot-lighttpd-1  | /openstreetmap-cgimap: Permission denied
troubleshoot-lighttpd-1  | 2024-04-17 20:51:39: (gw_backend.c.373) child exited: 13 unix:/tmp/map-fastcgi.socket-0
troubleshoot-lighttpd-1  | 2024-04-17 20:51:39: (gw_backend.c.656) gw-backend failed to start: /openstreetmap-cgimap
troubleshoot-lighttpd-1  | 2024-04-17 20:51:39: (gw_backend.c.658) If you're trying to run your app as a FastCGI backend, make sure you're using the FastCGI-enabled version.  If this is PHP on Gentoo, add 'fastcgi' to the USE flags.  If this is PHP, try removing the bytecode caches for now and try again.
troubleshoot-lighttpd-1  | 2024-04-17 20:51:39: (gw_backend.c.1700) [ERROR]: spawning gw failed.
troubleshoot-lighttpd-1  | 2024-04-17 20:51:39: (server.c.1572) Configuration of plugins failed. Going down.
troubleshoot-lighttpd-1 exited with code 255
```

I am sharing the docker compose snippet for lighttpd

```
version: "3.2"

services:
  lighttpd:
    image: sebp/lighttpd:latest
    volumes:
      - type: bind
        source: ./docker/lighttpd/config
        target: /etc/lighttpd
    ports:
      - "31500:31337"
    command:
      - start.sh
    depends_on:
      - cgimap
      - web
```
      
any suggestion to resolve this issue?
